import React, { useEffect } from 'react'
import Head from 'next/head'

import { getEthPrice } from '@/api/services'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home(): JSX.Element {

  useEffect(() => {
    getEthPrice()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main-content">HOLAAAAA</div>
        Hello suckers! jjjajaja</main>
    </>
  )
}
